---

#
# Install package
#

- name: Install hostapd
  package: name=hostapd state=present

- name: Install dnsmasq
  package: name=dnsmasq state=present

#
# Configure interface
#

- lineinfile: dest={{ interfaces_config_file }} regexp="^iface wlan0 inet" line="iface wlan0 inet static"
- lineinfile: dest={{ interfaces_config_file }} insertafter="^iface wlan0 inet" line="address 192.168.2.99"
- lineinfile: dest={{ interfaces_config_file }} insertafter="^iface wlan0 inet" line="netmask 255.255.255.0"

#
# Configure hostapd
#

- lineinfile: dest={{ hostapd_default_file }} regexp="^DAEMON_CONF=" line="DAEMON_CONF="/etc/hostapd/hostapd.conf""

- assert: { that: "hostapd_passphrase is defined" }

- template: src=templates/hostapd.conf.j2  dest={{ hostapd_config_file }} owner=root group=root mode=0644

#
# Configure dnsmasq
#

- lineinfile: dest={{ dnsmasq_conf_file }} regexp="^interface=" line="interface=wlan0"
- lineinfile: dest={{ dnsmasq_conf_file }} regexp="^dhcp-range=" line="dhcp-range=192.168.2.2,192.168.2.100,255.255.255.0,12h"

#
# Restart services
#

- service: name=hostapd state=restarted
- service: name=dnsmasq state=restarted

#
# Configure sysctl
#

- lineinfile: dest={{ sysctl_conf_file }} regexp="^net\.ipv4\.ip\_forward=" line="net.ipv4.ip_forward=1"

#
# Copy accesspoint
#

- copy: src=files/accesspoint dest={{ accesspoint_file }} owner=root group=root mode=0755
